apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: superheroe-golang-api-ing
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: superheroe-golang-api-svc
              servicePort: 8080
